# Generated by Django 5.1.1 on 2024-10-06 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=25, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('sucursal', models.CharField(max_length=100)),
                ('esActivo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SKU', models.CharField(max_length=15, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('marca', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ControlInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaInicio', models.DateField(auto_now=True)),
                ('fechaFin', models.DateField(blank=True, null=True)),
                ('esActivo', models.BooleanField(default=True)),
                ('cantArticulos', models.IntegerField(blank=True, null=True)),
                ('cantContada', models.IntegerField(default=0)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.almacen')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantContada', models.IntegerField(default=0)),
                ('stockSap', models.IntegerField()),
                ('diferencia', models.IntegerField()),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.controlinventario')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item')),
            ],
        ),
        migrations.CreateModel(
            name='RecuentoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaHora', models.DateField()),
                ('stockSap', models.IntegerField()),
                ('recuento', models.IntegerField()),
                ('detalleControl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.detallecontrol')),
            ],
        ),
    ]
